In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [40]:
data=pd.read_csv('heart.csv')
data.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  Heartfailure  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [41]:
data.sample(6)

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
786   69   M           NAP        140          254          0        LVH   
379   50   M           ASY        120            0          0         ST   
781   50   F           ASY        110          254          0        LVH   
65    37   F           ATA        120          260          0     Normal   
243   43   F           ATA        120          266          0     Normal   
539   57   M           ASY        110          197          0        LVH   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  Heartfailure  
786    146              N      2.0     Flat             1  
379    156              Y      0.0       Up             1  
781    159              N      0.0       Up             0  
65     130              N      0.0       Up             0  
243    118              N      0.0       Up             0  
539    100              N      0.0       Up             0

In [42]:
data.describe()

Age   RestingBP  Cholesterol   FastingBS       MaxHR  \
count  918.000000  918.000000   918.000000  918.000000  918.000000   
mean    53.510893  132.396514   198.799564    0.233115  136.809368   
std      9.432617   18.514154   109.384145    0.423046   25.460334   
min     28.000000    0.000000     0.000000    0.000000   60.000000   
25%     47.000000  120.000000   173.250000    0.000000  120.000000   
50%     54.000000  130.000000   223.000000    0.000000  138.000000   
75%     60.000000  140.000000   267.000000    0.000000  156.000000   
max     77.000000  200.000000   603.000000    1.000000  202.000000   

          Oldpeak  Heartfailure  
count  918.000000    918.000000  
mean     0.887364      0.553377  
std      1.066570      0.497414  
min     -2.600000      0.000000  
25%      0.000000      0.000000  
50%      0.600000      1.000000  
75%      1.500000      1.000000  
max      6.200000      1.000000

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Sex             918 non-null    object 
 2   ChestPainType   918 non-null    object 
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    object 
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    object 
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object 
 11  Heartfailure    918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB


In [44]:
data.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
Heartfailure      0
dtype: int64

In [45]:
data.shape

(918, 12)

In [46]:
data['ChestPainType'].unique()

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [47]:
data['RestingECG'].unique()

array(['Normal', 'ST', 'LVH'], dtype=object)

In [48]:
data['ST_Slope'].unique()

array(['Up', 'Flat', 'Down'], dtype=object)

In [49]:
#converting non-numeric data type in numeric

data['Sex']=data['Sex'].map({"M":0,"F":1})
data['ChestPainType']=data['ChestPainType'].map({"TA":0,"ATA":1,"NAP":2,"ASY":3})
data['RestingECG']=data['RestingECG'].map({"Normal":0,"ST":1,"LVH":2})
data['ExerciseAngina']=data['ExerciseAngina'].map({"Y":0,"N":1})
data['ST_Slope']=data['ST_Slope'].map({"Up":0,"Flat":1,"Down":2})

data

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0     40    0              1        140          289          0           0   
1     49    1              2        160          180          0           0   
2     37    0              1        130          283          0           1   
3     48    1              3        138          214          0           0   
4     54    0              2        150          195          0           0   
..   ...  ...            ...        ...          ...        ...         ...   
913   45    0              0        110          264          0           0   
914   68    0              3        144          193          1           0   
915   57    0              3        130          131          0           0   
916   57    1              1        130          236          0           2   
917   38    0              2        138          175          0           0   

     MaxHR  ExerciseAngina  Oldpeak  ST_Slope  Heartfailure  
0      172               1      0.0         0             0  
1      156               1      1.0         1             1  
2       98               1      0.0         0             0  
3      108               0      1.5         1             1  
4      122               1      0.0         0             0  
..     ...             ...      ...       ...           ...  
913    132               1      1.2         1             1  
914    141               1      3.4         1             1  
915    115               0      1.2         1             1  
916    174               1      0.0         1             1  
917    173               1      0.0         0             0  

[918 rows x 12 columns]

In [50]:
print(data.isnull().sum())
print(data.info)
numerical_features = ['Age', 'RestingBP', 'Cholesterol', 'MaxHR', 'Oldpeak']
for feature in numerical_features:
    plt.figure(figsize=(12, 6))
    plt.subplot(1, 2, 1)
    sns.histplot(data[feature], kde=True)
    plt.title(f'{feature} Distribution')
    
    plt.subplot(1, 2, 2)
    sns.boxplot(y=data[feature])
    plt.title(f'{feature} Boxplot')
    
    plt.show()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
Heartfailure      0
dtype: int64
<bound method DataFrame.info of      Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0     40    0              1        140          289          0           0   
1     49    1              2        160          180          0           0   
2     37    0              1        130          283          0           1   
3     48    1              3        138          214          0           0   
4     54    0              2        150          195          0           0   
..   ...  ...            ...        ...          ...        ...         ...   
913   45    0              0        110          264          0           0   
914   68    0              3        144          193          1           0   
915 

C:\Users\rajat\AppData\Local\Temp\ipykernel_20640\4287200705.py:14: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\rajat\AppData\Local\Temp\ipykernel_20640\4287200705.py:14: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\rajat\AppData\Local\Temp\ipykernel_20640\4287200705.py:14: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\rajat\AppData\Local\Temp\ipykernel_20640\4287200705.py:14: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\rajat\AppData\Local\Temp\ipykernel_20640\4287200705.py:14: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


In [51]:
len_live = len(data["Heartfailure"][data.Heartfailure == 0])
len_death = len(data["Heartfailure"][data.Heartfailure == 1])

arr = np.array([len_live , len_death]) 
labels = ['LIVING', 'DIED'] 
print("Total No. Of Living Cases :- ", len_live)
print("Total No. Of Died Cases :- ", len_death)

plt.pie(arr, labels=labels, explode = [0.2,0.0] , shadow=True,autopct='%1.1f%%') 
plt.show() 




Total No. Of Living Cases :-  410
Total No. Of Died Cases :-  508


C:\Users\rajat\AppData\Local\Temp\ipykernel_20640\2426311141.py:10: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


In [52]:
# import pandas as pd
# from ydata_profiling import ProfileReport

# # Load your dataset
# data = pd.read_csv('heart.csv')

# # Generate the profiling report
# profile = ProfileReport(data, title="Pandas Profiling Report", explorative=True)

# # Display the report in a Jupyter notebook
# profile.to_notebook_iframe()

# # Or save the report to an HTML file
# profile.to_file("your_report1.html")

In [53]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [54]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

In [55]:
# len(x_train)
#len(x_test)
# len(y_train)
len(y_test)

184

In [56]:
#scaling the model using standard method

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

x_train

array([[-1.24506731, -0.54060477, -0.29479827, ...,  0.83846064,
        -0.09706109,  2.25746543],
       [-1.8862362 , -0.54060477, -0.29479827, ...,  0.83846064,
        -0.83628643, -1.07985506],
       [ 0.25099346, -0.54060477,  0.79803975, ..., -1.19266183,
         0.08774524,  0.58880518],
       ...,
       [ 0.67843939, -0.54060477,  0.79803975, ..., -1.19266183,
         0.45735791, -1.07985506],
       [ 0.67843939, -0.54060477,  0.79803975, ..., -1.19266183,
        -0.83628643, -1.07985506],
       [-1.45879027,  1.84978019,  0.79803975, ...,  0.83846064,
         1.01177691,  0.58880518]])

In [57]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,accuracy_score,r2_score,classification_report
regressor=LogisticRegression(   random_state=42,
                                # penalty='l2' ,#Effective regularization for a small dataset like prevent overfitting
                                solver='liblinear'  #handle diffrent types of regularization
                            )
regressor.fit(x_train,y_train)
y_pred=regressor.predict(x_test)


print("r**2 score is",r2_score(y_test,y_pred))
print("Accuracy Score: ",accuracy_score(y_test,y_pred))
print("confusion matrix:\n",confusion_matrix(y_test,y_pred))
print("classification_report:\n",classification_report(y_test,y_pred))



r**2 score is 0.3523485859934459
Accuracy Score:  0.842391304347826
confusion matrix:
 [[68  9]
 [20 87]]
classification_report:
               precision    recall  f1-score   support

           0       0.77      0.88      0.82        77
           1       0.91      0.81      0.86       107

    accuracy                           0.84       184
   macro avg       0.84      0.85      0.84       184
weighted avg       0.85      0.84      0.84       184



In [58]:
from sklearn.ensemble import RandomForestClassifier
forest=RandomForestClassifier(n_estimators=100,random_state=40)
forest.fit(x_train,y_train)
y_pred=forest.predict(x_test)

print("Accuracy score: ",accuracy_score(y_test,y_pred))
print("R**2 score: ",r2_score(y_test,y_pred))
print("confusion matrix\n:",confusion_matrix(y_test,y_pred))
print("classification_report\n:",classification_report(y_test,y_pred))

Accuracy score:  0.8913043478260869
R**2 score:  0.5533438524092731
confusion matrix
: [[69  8]
 [12 95]]
classification_report
:               precision    recall  f1-score   support

           0       0.85      0.90      0.87        77
           1       0.92      0.89      0.90       107

    accuracy                           0.89       184
   macro avg       0.89      0.89      0.89       184
weighted avg       0.89      0.89      0.89       184



In [59]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(max_depth=60 ,random_state=42)

model.fit(x_train,y_train)
y_pred=model.predict(x_test)

print("Accuracy score: ",accuracy_score(y_test,y_pred))
print("R**2 score: ",r2_score(y_test,y_pred))
print("confusion matrix\n:",confusion_matrix(y_test,y_pred))
print("classification_report\n:",classification_report(y_test,y_pred))

Accuracy score:  0.8152173913043478
R**2 score:  0.2406845490957641
confusion matrix
: [[65 12]
 [22 85]]
classification_report
:               precision    recall  f1-score   support

           0       0.75      0.84      0.79        77
           1       0.88      0.79      0.83       107

    accuracy                           0.82       184
   macro avg       0.81      0.82      0.81       184
weighted avg       0.82      0.82      0.82       184



In [60]:
#knn clasifier

from sklearn.neighbors import KNeighborsClassifier
k=8
knn=KNeighborsClassifier(n_neighbors=k)
knn.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 8,
 'p': 2,
 'weights': 'uniform'}

In [61]:
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
                                                                                                                                                                                        
print("Accuracy Score: ",accuracy_score(y_test,y_pred))
print("R*2 score:\n",r2_score(y_test,y_pred))
print("confusion matrix\n:",confusion_matrix(y_test,y_pred))
print("Classification report:\n",classification_report(y_test,y_pred))

Accuracy Score:  0.842391304347826
R*2 score:
 0.3523485859934459
confusion matrix
: [[69  8]
 [21 86]]
Classification report:
               precision    recall  f1-score   support

           0       0.77      0.90      0.83        77
           1       0.91      0.80      0.86       107

    accuracy                           0.84       184
   macro avg       0.84      0.85      0.84       184
weighted avg       0.85      0.84      0.84       184



In [62]:
#use of hyperparameter

from sklearn.model_selection import RandomizedSearchCV
model=RandomForestClassifier()

parameter={
    'n_estimators': np.arange(1,100,5),   #best 51              # Number of trees in the forest
    'max_depth': [None, 10, 20, 30, 40],    #40             # Maximum depth of the tree
    'max_features': [ 'sqrt', 'log2'],            # Number of features to consider for the best split
    'criterion': ['gini', 'entropy'],
         
}

random=RandomizedSearchCV(
  model,
  parameter,
  n_iter=100,  #no of times you run the model
  cv=5,       #Cross validation folds
  n_jobs=-1   #use the cpu cores speeding up the process by running tasks in parallel. 
)

random.fit(x_train,y_train)
y_pred=random.predict(x_test)

print("best parameter used: \n",random.best_params_)
print("Accuracy score: ",accuracy_score(y_test,y_pred))
print("R*2 score: ",r2_score(y_test,y_pred))
print("confusion matrix:\n ",confusion_matrix(y_test,y_pred))
print("classification report:\n",classification_report(y_test,y_pred))


best parameter used: 
 {'n_estimators': 91, 'max_features': 'sqrt', 'max_depth': 10, 'criterion': 'gini'}
Accuracy score:  0.8695652173913043
R*2 score:  0.46401262289112766
confusion matrix:
  [[68  9]
 [15 92]]
classification report:
               precision    recall  f1-score   support

           0       0.82      0.88      0.85        77
           1       0.91      0.86      0.88       107

    accuracy                           0.87       184
   macro avg       0.87      0.87      0.87       184
weighted avg       0.87      0.87      0.87       184



In [63]:
#use of hyperparameter grid search

from sklearn.model_selection import GridSearchCV
model=RandomForestClassifier()

parameter={
    'n_estimators': np.arange(1,50,1),                 # Number of trees in the forest
    'max_depth': [None, 10, 20, 30, 40],                 # Maximum depth of the tree
    'max_features': [ 'sqrt', 'log2'],            # Number of features to consider for the best split
    'criterion': ['gini', 'entropy']
         
}

grid=GridSearchCV(
  model,
  parameter,
  cv=5,       #Cross validation folds
  n_jobs=-1   #use the cpu cores speeding up the process by running tasks in parallel. 
)

grid.fit(x_train,y_train)
y_pred=grid.predict(x_test)

print("best parameter used: \n",grid.best_params_)
print("best score is:",grid.best_score_)
print("Accuracy score: ",accuracy_score(y_test,y_pred))
print("R*2 score: ",r2_score(y_test,y_pred))
print("confusion matrix:\n ",confusion_matrix(y_test,y_pred))
print("classification report:\n",classification_report(y_test,y_pred))


KeyboardInterrupt: 

In [27]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import numpy as np


model = KNeighborsClassifier()

# Define the parameter grid
parameter_grid = {
    'algorithm': ['auto', 'ball_tree', 'kd_tree'],
    'leaf_size': np.arange(1, 50, 1), 
    'metric': ['euclidean', 'manhattan'], 
    'n_neighbors': [3, 5, 7, 10],
    'n_jobs': [-1, None],
    'p': [1, 2],
    'weights': ['uniform', 'distance']  
}

# Initialize GridSearchCV
gridk = GridSearchCV(
    model,
    param_grid=parameter_grid,  # Use param_grid instead of param_distributions
    cv=5,                       # Cross-validation folds
    n_jobs=-1,              # Use all available CPU cores
    
    
    
)


gridk.fit(x_train, y_train)

y_pred = gridk.predict(x_test)

# Print the best parameters and evaluation metrics
print("Best parameters used:\n", gridk.best_params_)
print("the best score is:",gridk.best_score_)
print("Accuracy score: ", accuracy_score(y_test, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification report:\n", classification_report(y_test, y_pred))


Best parameters used:
 {'algorithm': 'auto', 'leaf_size': 1, 'metric': 'euclidean', 'n_jobs': -1, 'n_neighbors': 7, 'p': 1, 'weights': 'uniform'}
the best score is: 0.871941105209207
Accuracy score:  0.842391304347826
Confusion matrix:
 [[66 11]
 [18 89]]
Classification report:
               precision    recall  f1-score   support

           0       0.79      0.86      0.82        77
           1       0.89      0.83      0.86       107

    accuracy                           0.84       184
   macro avg       0.84      0.84      0.84       184
weighted avg       0.85      0.84      0.84       184



In [28]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import numpy as np


model = KNeighborsClassifier()


parameter_dist = {
    'algorithm': ['auto', 'ball_tree', 'kd_tree'],
    'leaf_size': np.arange(1, 50, 1), 
    'metric': ['euclidean', 'manhattan'], 
    'n_neighbors': [3, 5, 7, 10],  
    'n_jobs': [-1, None],
    'p': [1, 2],
    'weights': ['uniform', 'distance']  
}

# Initialize RandomizedSearchCV
random_search = RandomizedSearchCV(
    model,
    param_distributions=parameter_dist,  # Parameter distribution
    n_iter=100,  # Number of parameter settings to sample
    cv=5,        # Cross-validation folds
    n_jobs=-1,   # Use all available CPU cores
    random_state=42  # Seed for reproducibility
)


random_search.fit(x_train, y_train)


y_pred = random_search.predict(x_test)

print("best score: ",random_search.best_score_)
print("Best parameters used:\n", random_search.best_params_)
print("Accuracy score: ", accuracy_score(y_test, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification report:\n", classification_report(y_test, y_pred))


best score:  0.871941105209207
Best parameters used:
 {'weights': 'uniform', 'p': 1, 'n_neighbors': 7, 'n_jobs': -1, 'metric': 'euclidean', 'leaf_size': 19, 'algorithm': 'ball_tree'}
Accuracy score:  0.842391304347826
Confusion matrix:
 [[66 11]
 [18 89]]
Classification report:
               precision    recall  f1-score   support

           0       0.79      0.86      0.82        77
           1       0.89      0.83      0.86       107

    accuracy                           0.84       184
   macro avg       0.84      0.84      0.84       184
weighted avg       0.85      0.84      0.84       184



In [29]:
#cross validation

from sklearn import svm
from sklearn.model_selection import cross_val_score

clm=svm.SVC(kernel='rbf',C=1).fit(x_train,y_train)
clm.score(x_test,y_test)

scores=cross_val_score(clm,x_train,y_train,cv=5)
print(scores)
scores.mean()

[0.89795918 0.89115646 0.85034014 0.82312925 0.85616438]


0.8637498835150497

In [30]:
from sklearn.ensemble import GradientBoostingClassifier


X=data.drop('Heartfailure',axis=1)
y=data['Heartfailure']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)


scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

model=GradientBoostingClassifier(loss='exponential',learning_rate=0.3,n_estimators=16,max_depth=5)


model.fit(X_train,y_train)

y_pred=model.predict(X_test)
r2=r2_score(y_test,y_pred)
print("R2:",r2)
print(f"Accuracy is:{accuracy_score(y_test,y_pred)}")
print(f"Confusion matrix:\n{confusion_matrix(y_test,y_pred)}")
print(f"Classification Report:\n{classification_report(y_test,y_pred)}")

R2: 0.3970142007525186
Accuracy is:0.8532608695652174
Confusion matrix:
[[62 15]
 [12 95]]
Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.81      0.82        77
           1       0.86      0.89      0.88       107

    accuracy                           0.85       184
   macro avg       0.85      0.85      0.85       184
weighted avg       0.85      0.85      0.85       184



In [31]:
# sns.boxplot(data['Cholesterol'])

Q1=data['Cholesterol'].quantile(0.25)
Q3=data['Cholesterol'].quantile(0.75)

IQR=Q3-Q1
lowerBound=Q1-1.5*IQR
upperBound=Q3+1.5*IQR

print(IQR)
print("lower outlier: ",lowerBound)
print("upper outlier: ",upperBound)

filterData=data[((data['Cholesterol'])>=lowerBound) & (data['Cholesterol']<=upperBound)]
# print("FilterDta:\n",filterData)

Q1=filterData['RestingBP'].quantile(0.25)
Q3=filterData['RestingBP'].quantile(0.75)

IQR=Q3-Q1
lowerBound=Q1-1.5*IQR
upperBound=Q3+1.5*IQR

print(IQR)
print("lower outlier: ",lowerBound)
print("upper outlier: ",upperBound)

filterData=filterData[((filterData['RestingBP'])>=lowerBound) & (filterData['RestingBP']<=upperBound)]
print("filterdata:\n",filterData)

# sns.boxplot(filterData['RestingBP'])


Q1=filterData['Oldpeak'].quantile(0.25)
Q3=filterData['Oldpeak'].quantile(0.75)

IQR=Q3-Q1
lowerBound=Q1-1.5*IQR
upperBound=Q3+1.5*IQR

print(IQR)
print("lower outlier: ",lowerBound)
print("upper outlier: ",upperBound)

filterData=filterData[((filterData['Oldpeak'])>=lowerBound) & (filterData['Oldpeak']<=upperBound)]
print("filterdata:\n",filterData)

sns.boxplot(filterData['Oldpeak'])



93.75
lower outlier:  32.625
upper outlier:  407.625
20.0
lower outlier:  90.0
upper outlier:  170.0
filterdata:
      Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0     40    0              1        140          289          0           0   
1     49    1              2        160          180          0           0   
2     37    0              1        130          283          0           1   
3     48    1              3        138          214          0           0   
4     54    0              2        150          195          0           0   
..   ...  ...            ...        ...          ...        ...         ...   
913   45    0              0        110          264          0           0   
914   68    0              3        144          193          1           0   
915   57    0              3        130          131          0           0   
916   57    1              1        130          236          0           2   
917   38    0    

c:\Users\rajat\AppData\Local\Programs\Python\Python312\Lib\site-packages\seaborn\categorical.py:379: UserWarning: Attempting to set identical low and high xlims makes transformation singular; automatically expanding.
  ax.set_xlim(-.5, n - .5, auto=None)


<Axes: title={'center': 'Oldpeak Boxplot'}, ylabel='Oldpeak'>

In [32]:


X=filterData.drop('Heartfailure',axis=1)
y=filterData['Heartfailure']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)


scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)


model=RandomForestClassifier(n_estimators= 858, min_samples_split= 12,
                             min_samples_leaf= 1, max_features= 'sqrt', max_depth=33,criterion='gini',bootstrap=True)


model.fit(X_train,y_train)

scores = cross_val_score(model, X, y, cv=5, scoring='accuracy')

# Print the scores for each fold
print("Cross-validation scores:", scores)
print("Mean accuracy:", scores.mean())
print("Standard deviation:", scores.std())


y_pred=model.predict(X_test)
r2=r2_score(y_test,y_pred)
print("R2:",r2)
print(f"Accuracy is:{accuracy_score(y_test,y_pred)}")
print(f"Confusion matrix:\n{confusion_matrix(y_test,y_pred)}")
print(f"Classification Report:\n{classification_report(y_test,y_pred)}")

Cross-validation scores: [0.89361702 0.95035461 0.9        0.79285714 0.76428571]
Mean accuracy: 0.8602228976697062
Standard deviation: 0.07009022612774651
R2: 0.5460764587525149
Accuracy is:0.8865248226950354
Confusion matrix:
[[64  7]
 [ 9 61]]
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.90      0.89        71
           1       0.90      0.87      0.88        70

    accuracy                           0.89       141
   macro avg       0.89      0.89      0.89       141
weighted avg       0.89      0.89      0.89       141



In [33]:
from sklearn.ensemble import GradientBoostingClassifier,HistGradientBoostingClassifier
from sklearn.model_selection import RandomizedSearchCV

X=filterData.drop('Heartfailure',axis=1)
y=filterData['Heartfailure']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.21,random_state=42)

param_distributions = {
    'n_estimators':[i for i in range(100,1000)],  # Number of trees in the forest
    'max_depth': [i for i in range(10,100)],       # Maximum depth of the tree
    'min_samples_split': [i for i in range(2,20)], # Minimum number of samples required to split a node
    'min_samples_leaf': [i for i in range(1,20)],  # Minimum number of samples required at a leaf node
    'max_features': ['sqrt', 'log2'], # Number of features to consider when looking for the best split
    'bootstrap': [True, False],          # Whether bootstrap samples are used when building trees
    'criterion': ['gini', 'entropy']    # Function to measure the quality of a split

}

scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)
model=RandomForestClassifier(random_state=42)

model=RandomForestClassifier(n_estimators= 300, min_samples_split= 19,
                             min_samples_leaf= 3,n_jobs=-1, max_features= 'log2', max_depth=10,criterion='gini',bootstrap=False, random_state=42)
# random_search = RandomizedSearchCV(estimator=model, param_distributions=param_distributions,
#                                    n_iter=100, cv=5, n_jobs=-1, verbose=2, scoring='accuracy')


# random_search.fit(X_train, y_train)

# best_params = random_search.best_params_
# print("Best parameters found: ", best_params)
# print(f"best score is:{random_search.best_score_}")
model.fit(X_train,y_train)

scores = cross_val_score(model, X, y, cv=15, scoring=('accuracy'))

# Print the scores for each fold
print("Cross-validation scores:", scores)
print("Mean accuracy:", scores.mean())
print("Standard deviation:", scores.std())


y_pred=model.predict(X_test)
r2=r2_score(y_test,y_pred)
print("R2:",r2)
print(f"Accuracy is:{accuracy_score(y_test,y_pred)}")
print(f"Confusion matrix:\n{confusion_matrix(y_test,y_pred)}")
print(f"Classification Report:\n{classification_report(y_test,y_pred)}")



Cross-validation scores: [0.91489362 0.91489362 0.91489362 0.95744681 0.91489362 0.9787234
 0.9787234  0.91489362 0.82978723 0.80851064 0.76595745 0.82978723
 0.76086957 0.7826087  0.7826087 ]
Mean accuracy: 0.8699660807893925
Standard deviation: 0.07589006438663125
R2: 0.702648401826484
Accuracy is:0.9256756756756757
Confusion matrix:
[[68  7]
 [ 4 69]]
Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.91      0.93        75
           1       0.91      0.95      0.93        73

    accuracy                           0.93       148
   macro avg       0.93      0.93      0.93       148
weighted avg       0.93      0.93      0.93       148



In [34]:
# import pandas as pd
from ydata_profiling import ProfileReport

# Load your dataset
# filterdata = pd.read_csv('heart.csv')

# Generate the profiling report
profile = ProfileReport(filterData, title="Pandas Profiling Report", explorative=True)

# Display the report in a Jupyter notebook
profile.to_notebook_iframe()

# Or save the report to an HTML file
profile.to_file("your_report_3.html")

ModuleNotFoundError: No module named 'ydata_profiling'

In [35]:
len_live = len(filterData["Heartfailure"][filterData.Heartfailure == 0])
len_death = len(filterData["Heartfailure"][filterData.Heartfailure == 1])

arr = np.array([len_live , len_death]) 
labels = ['LIVING', 'DIED'] 
print("Total No. Of Living Cases :- ", len_live)
print("Total No. Of Died Cases :- ", len_death)

plt.pie(arr, labels=labels, explode = [0.2,0.0] , shadow=True,autopct='%1.1f%%') 
plt.show() 


Total No. Of Living Cases :-  377
Total No. Of Died Cases :-  325


C:\Users\rajat\AppData\Local\Temp\ipykernel_20640\1527719231.py:10: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


In [64]:
model_path = 'heart_failure_model.pkl'
with open(model_path, 'wb') as file:
    pickle.dump(model, file)

In [37]:
import pickle

In [65]:
import streamlit as st
import pandas as pd

# Assuming the model and scaler have already been trained in previous steps

# Function to get user input and predict heart failure
def predict_heart_failure(model, scaler):
    st.title("Heart Failure Prediction")
    
    st.write("Please provide the following details for prediction:")

    # Collect user inputs using Streamlit's sidebar
    Age = st.number_input("Age", min_value=0, max_value=120, value=25)
    Sex = st.selectbox("Sex", options=[0, 1], format_func=lambda x: "Female" if x == 0 else "Male")
    ChestPainType = st.selectbox("Chest Pain Type", options=[0, 1, 2, 3], 
                                  format_func=lambda x: ["Typical Angina", "Atypical Angina", "Non-Anginal Pain", "Asymptomatic"][x])
    RestingBP = st.number_input("Resting Blood Pressure", min_value=50, max_value=200, value=120)
    Cholesterol = st.number_input("Cholesterol Level", min_value=0, max_value=600, value=200)
    FastingBS = st.selectbox("Fasting Blood Sugar", options=[0, 1], format_func=lambda x: "No" if x == 0 else "Yes")
    RestingECG = st.selectbox("Resting ECG", options=[0, 1, 2], 
                               format_func=lambda x: ["Normal", "Abnormal", "Hypertrophy"][x])
    MaxHR = st.number_input("Maximum Heart Rate Achieved", min_value=60, max_value=220, value=100)
    ExerciseAngina = st.selectbox("Exercise Induced Angina", options=[0, 1], format_func=lambda x: "No" if x == 0 else "Yes")
    Oldpeak = st.number_input("Oldpeak (ST Depression)", min_value=0.0, max_value=6.0, value=1.0, step=0.1)
    ST_Slope = st.selectbox("ST Slope", options=[0, 1, 2], 
                             format_func=lambda x: ["Upsloping", "Flat", "Downsloping"][x])

    # Create a DataFrame for the input values
    input_data = pd.DataFrame({
        'Age': [Age],
        'Sex': [Sex],
        'ChestPainType': [ChestPainType],
        'RestingBP': [RestingBP],
        'Cholesterol': [Cholesterol],
        'FastingBS': [FastingBS],
        'RestingECG': [RestingECG],
        'MaxHR': [MaxHR],
        'ExerciseAngina': [ExerciseAngina],
        'Oldpeak': [Oldpeak],
        'ST_Slope': [ST_Slope]
    })

    # Preprocess the input (scaling)
    input_data_scaled = scaler.transform(input_data)

    # Make a prediction using the trained model
    if st.button("Predict"):
        prediction = model.predict(input_data_scaled)

        # Output the prediction
        if prediction[0] == 1:
            st.success("Prediction: YES, the customer is at risk of heart failure.")
        else:
            st.success("Prediction: NO, the customer is not at risk of heart failure.")

# Call the function to get input and predict
predict_heart_failure(model, scaler)

2024-09-22 01:09:47.801 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-22 01:09:47.978 
  command:

    streamlit run C:\Users\rajat\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py [ARGUMENTS]
2024-09-22 01:09:47.979 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-22 01:09:47.980 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-22 01:09:47.980 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-22 01:09:47.980 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-22 01:09:47.980 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-22 01:09:47.981 Thre

SyntaxError: invalid syntax (1432270806.py, line 1)